# Generated by Django 4.2.13 on 2024-06-10 19:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurant_site', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='booked_on',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='message_to_restaurant',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='number_of_guests',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='number_of_tables',
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_email',
            field=models.EmailField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_name',
            field=models.CharField(blank=True, max_length=200, unique=True),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_tables', models.IntegerField(default=0, unique=True)),
                ('number_of_guests', models.IntegerField(default=0, unique=True)),
                ('message_to_restaurant', models.TextField(blank=True)),
                ('booked_on', models.DateTimeField(auto_now_add=True)),
                ('booking_relationship_to_Customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_booking', to='restaurant_site.customer')),
                ('customer_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_booking', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
