# Generated by Django 4.2.13 on 2024-11-14 20:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_user', models.CharField(max_length=50)),
                ('email_user', models.EmailField(blank=True, max_length=50)),
                ('phone_user', models.CharField(default=None, max_length=30)),
                ('number_of_guests', models.IntegerField()),
                ('date_of_month', models.DateField(default=None)),
                ('time_of_day', models.TimeField(default=None)),
                ('message_to_restaurant', models.TextField(blank=True, max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
