# Generated by Django 4.2.13 on 2024-06-11 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.IntegerField()),
                ('number_of_guests', models.IntegerField(default=0, unique=True)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
        ),
    ]
