# Generated by Django 4.2.13 on 2024-06-13 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_cancelbooking_customer_remove_booking_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.customer'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='number_of_guests',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='cancelbooking',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
