# Generated by Django 4.2.13 on 2024-07-20 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_reservation_message_to_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='number_of_guests',
            field=models.PositiveIntegerField(),
        ),
    ]
