# Generated by Django 4.2.13 on 2024-08-06 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_reservation_number_of_guests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='status',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='phone_user',
            field=models.CharField(default=None, max_length=15),
        ),
    ]
