# Generated by Django 4.2.13 on 2024-06-13 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_booking_customer_alter_booking_number_of_guests_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancelbooking',
            name='booking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.booking'),
        ),
    ]
