# Generated by Django 4.2.13 on 2024-06-16 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_cancelbooking_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(blank=True, max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('number_of_guests', models.IntegerField(default=0, unique=True)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('message_to_restaurant', models.CharField(blank=True, max_length=100)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.customer')),
            ],
        ),
    ]
